env:
   global:
     - CONAN_REFERENCE: "Boost.Beast/1.65.0"
     - CONAN_SUBJECT: "bincrafters"
     - CONAN_CHANNEL: "ci"
     - CONAN_REPO: "public-conan"

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh
  
script:
  - export CONAN_REFERENCE_FULL=${CONAN_REFERENCE}@${CONAN_SUBJECT}/${CONAN_CHANNEL}
  - echo ${CONAN_REFERENCE_FULL}
  - conan create ${CONAN_SUBJECT}/${CONAN_CHANNEL}
  - conan remote add ${CONAN_SUBJECT} "https://api.bintray.com/conan/${CONAN_SUBJECT}/${CONAN_REPO}"
  - conan remote add_ref ${CONAN_REFERENCE_FULL} ${CONAN_SUBJECT}
  - conan user -p ${CONAN_KEY} --remote ${CONAN_SUBJECT} ${CONAN_USER}
  - conan upload ${CONAN_REFERENCE_FULL} --all
