env:
   global:
     - CONAN_REFERENCE: "Boost.Beast/1.65.0"
     - CONAN_CHANNEL: "ci"
     - CONAN_STABLE_BRANCH_PATTERN: "release/*"
     - CONAN_TOTAL_PAGES: 1

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:

      - <<: *linux
         env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_ARCHS=x86 CONAN_CURRENT_PAGE=1

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
